### ISSUE TITLE
Code to run piecewise NFs? 

### ISSUE THREAD

**Issue by ImahnShekhzadeh** [htjb/piecewise_normalizing_flows#1]
Hi, 

I think this is a really nice paper you have brougt out :slightly_smiling_face: 

Currently, the code to run the piecewise NFs is missing, do you intend to include it at some point? If yes, can you roughly assess how long it will take?

**Comment by htjb** [comment]
Hi @ImahnShekhzadeh, thanks for the message and glad you liked the paper! The piecewise NFs are implemented in our code [margarine](https://github.com/htjb/margarine), and you need to install this to run the experiments in this repository. Sorry if this wasn't clear! I will update the readme.

You should install `margarine` from the repo (the pip is a bit behind). The following example shows you how to train a piecewise normalising flow, sample from it and calculate log probabilities.

```python
from margarine.maf import MAF

# here I am assuming your samples are in a numpy array theta and there is a corresponding set of weights
# setting clustering=True sets this up as a piecewise normalising flow
flow = MAF(theta, weights, clustering=True)

# train the maf
flow.train(5000, early_stop=True)

# margarine samples from the clusters as described in the paper
samples = flow.sample(5000)

# and calcualtes probabilities too
log_prob = flow.log_prob(samples)
```

Hope that helps! I'll make sure I update the readme. 😄

**Comment by ImahnShekhzadeh** [comment]
Thanks for the reply! Follow-up question: 

In the `MAF` class from `margarine`, it is necessary to specify `weights` (which you also posted in your code snippet). However, I would naively have thought that `weights` is calculated internally by taking the number of theta's that are in each cluster `j` divided by the total number of samples, i.e. `w_j = N_j / N`. This is what is done for sampling, can you comment why `weights` has to be specified a priori during training? :slightly_smiling_face:

**Comment by htjb** [comment]
The `weights` that you supply to `MAF` are the sample weights, not the weights of the clusters. Sample weights are derived when we run nested sampling, for example, on some likelihood function, and they quantify the relative importance of the samples in `theta`. If your sample points in `theta` are evenly weighted, i.e. all as important as each other, you can call the `MAF` class as follows

```python
flow = MAF(theta, np.ones(len(theta)), clustering=True)
```

Really weights should be a kwarg that defaults to `np.ones(len(theta))` but I tend to work with weighted samples quite a lot!

The weights of the clusters `w_j = N_j/N` are indeed calculated internally.
